//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VHMEXEntities : DbContext
    {
        public VHMEXEntities()
            : base("name=VHMEXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_actividades> tbl_actividades { get; set; }
        public virtual DbSet<tbl_Asistencia> tbl_Asistencia { get; set; }
        public virtual DbSet<tbl_criteriosDeEvaluacion> tbl_criteriosDeEvaluacion { get; set; }
        public virtual DbSet<tbl_evaluacion> tbl_evaluacion { get; set; }
        public virtual DbSet<tbl_grado> tbl_grado { get; set; }
        public virtual DbSet<tbl_grupo> tbl_grupo { get; set; }
        public virtual DbSet<tbl_materia> tbl_materia { get; set; }
        public virtual DbSet<tbl_nivel> tbl_nivel { get; set; }
        public virtual DbSet<tbl_nivel_grado> tbl_nivel_grado { get; set; }
        public virtual DbSet<tbl_nivel_materia> tbl_nivel_materia { get; set; }
        public virtual DbSet<tbl_periodo> tbl_periodo { get; set; }
        public virtual DbSet<tbl_periodo_nivel> tbl_periodo_nivel { get; set; }
        public virtual DbSet<tbl_rol> tbl_rol { get; set; }
        public virtual DbSet<tbl_rol_operacion> tbl_rol_operacion { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
        public virtual DbSet<tbl_usuario_periodo> tbl_usuario_periodo { get; set; }
        public virtual DbSet<tbl_usuario_rol> tbl_usuario_rol { get; set; }
    }
}
