//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_criteriosDeEvaluacion
    {
        public int idCriterio { get; set; }
        public string criterio { get; set; }
        public int porcentaje { get; set; }
        public int idMateria { get; set; }
    
        public virtual tbl_materia tbl_materia { get; set; }
    }
}
