//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Asistencia
    {
        public int idAsistencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idEvaluacion { get; set; }
    
        public virtual tbl_evaluacion tbl_evaluacion { get; set; }
    }
}
