//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_nivel_grado
    {
        public int idNivelGrado { get; set; }
        public int idNivel { get; set; }
        public int idGrado { get; set; }
    
        public virtual tbl_grado tbl_grado { get; set; }
        public virtual tbl_nivel tbl_nivel { get; set; }
    }
}
