//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_nivel_materia
    {
        public int idNivelMateria { get; set; }
        public int idNivel { get; set; }
        public int idMateria { get; set; }
    
        public virtual tbl_materia tbl_materia { get; set; }
        public virtual tbl_nivel tbl_nivel { get; set; }
    }
}
