//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario_periodo
    {
        public int idUsuarioPeriodo { get; set; }
        public int idUsuario { get; set; }
        public int idPeriodo { get; set; }
    
        public virtual tbl_periodo tbl_periodo { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
