//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_periodo_nivel
    {
        public int idPeridoNivel { get; set; }
        public int idPeriodo { get; set; }
        public int idNivel { get; set; }
    
        public virtual tbl_nivel tbl_nivel { get; set; }
        public virtual tbl_periodo tbl_periodo { get; set; }
    }
}
