//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actividad()
        {
            this.AlumnoActividad = new HashSet<AlumnoActividad>();
        }
    
        public int idActividad { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
        public int idDocente { get; set; }
        public string Nombre { get; set; }
        public int idDocMat { get; set; }
        public Nullable<int> valor { get; set; }
        public Nullable<int> idDocenteGrupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoActividad> AlumnoActividad { get; set; }
        public virtual Docente Docente { get; set; }
        public virtual DocenteGrupo DocenteGrupo { get; set; }
        public virtual DocenteMateria DocenteMateria { get; set; }
    }
}
