//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoAsistencia
    {
        public int idAlumno { get; set; }
        public int idAsistencia { get; set; }
        public int idCicloEscolar { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Asistencia Asistencia { get; set; }
        public virtual CicloEscolar CicloEscolar { get; set; }
    }
}
