//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoGrupo
    {
        public int idAlumno { get; set; }
        public int idGradoGrupo { get; set; }
        public Nullable<int> idAlumnoGrupo { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Grado_Grupo Grado_Grupo { get; set; }
    }
}
