//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asistencia()
        {
            this.AlumnoAsistencia = new HashSet<AlumnoAsistencia>();
        }
    
        public int idAsistencia { get; set; }
        public System.DateTime fecha { get; set; }
        public int idPresente { get; set; }
        public int idGradoGrupo { get; set; }
        public Nullable<int> idDocenteGrupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoAsistencia> AlumnoAsistencia { get; set; }
        public virtual DocenteGrupo DocenteGrupo { get; set; }
        public virtual Grado_Grupo Grado_Grupo { get; set; }
        public virtual Presente Presente { get; set; }
    }
}
