//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CicloEscolarGrupo
    {
        public int idCicloEscolar { get; set; }
        public int idGradoGrupo { get; set; }
        public int idCicloEscolarGrupo { get; set; }
    
        public virtual CicloEscolar CicloEscolar { get; set; }
        public virtual Grado_Grupo Grado_Grupo { get; set; }
    }
}
