//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CicloEscolarPlan
    {
        public int idCicloEscolar { get; set; }
        public int idPlanEstudio { get; set; }
        public int idCicloEscolarPlan { get; set; }
    
        public virtual CicloEscolar CicloEscolar { get; set; }
        public virtual PlanDeEstudio PlanDeEstudio { get; set; }
    }
}
