//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterios
    {
        public int idCriterio { get; set; }
        public int criterioAsistencia { get; set; }
        public int criterioExamen { get; set; }
        public int criterioTareas { get; set; }
        public int criterioActividades { get; set; }
        public int idMateria { get; set; }
    
        public virtual Materia Materia { get; set; }
    }
}
