//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grado_Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grado_Grupo()
        {
            this.AlumnoGrupo = new HashSet<AlumnoGrupo>();
            this.Asistencia = new HashSet<Asistencia>();
            this.CicloEscolarGrupo = new HashSet<CicloEscolarGrupo>();
            this.DocenteGrupo = new HashSet<DocenteGrupo>();
        }
    
        public int idGradoGrupo { get; set; }
        public int idGrado { get; set; }
        public int idGrupo { get; set; }
        public int idNivel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoGrupo> AlumnoGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CicloEscolarGrupo> CicloEscolarGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocenteGrupo> DocenteGrupo { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual nivel nivel { get; set; }
    }
}
