//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vhmexEntities : DbContext
    {
        public vhmexEntities()
            : base("name=vhmexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumnoActividad> AlumnoActividad { get; set; }
        public virtual DbSet<AlumnoAsistencia> AlumnoAsistencia { get; set; }
        public virtual DbSet<AlumnoCalificacion> AlumnoCalificacion { get; set; }
        public virtual DbSet<AlumnoGrupo> AlumnoGrupo { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Calificacion> Calificacion { get; set; }
        public virtual DbSet<CicloEscolar> CicloEscolar { get; set; }
        public virtual DbSet<CicloEscolarGrupo> CicloEscolarGrupo { get; set; }
        public virtual DbSet<CicloEscolarPlan> CicloEscolarPlan { get; set; }
        public virtual DbSet<Criterios> Criterios { get; set; }
        public virtual DbSet<Docente> Docente { get; set; }
        public virtual DbSet<DocenteGrupo> DocenteGrupo { get; set; }
        public virtual DbSet<DocenteMateria> DocenteMateria { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<Examen> Examen { get; set; }
        public virtual DbSet<ExamenAlumno> ExamenAlumno { get; set; }
        public virtual DbSet<Grado> Grado { get; set; }
        public virtual DbSet<Grado_Grupo> Grado_Grupo { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<nivel> nivel { get; set; }
        public virtual DbSet<PadreAlumno> PadreAlumno { get; set; }
        public virtual DbSet<PadreDeFamilia> PadreDeFamilia { get; set; }
        public virtual DbSet<PlanDeEstudio> PlanDeEstudio { get; set; }
        public virtual DbSet<Presente> Presente { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<TareaAlumno> TareaAlumno { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }
    }
}
