//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaAlumno
    {
        public int idTarea { get; set; }
        public int idAlumno { get; set; }
        public int idCicloEscolar { get; set; }
        public int idTareaAlumno { get; set; }
        public Nullable<int> puntos { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual CicloEscolar CicloEscolar { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
