//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarea()
        {
            this.TareaAlumno = new HashSet<TareaAlumno>();
        }
    
        public int idTarea { get; set; }
        public string Nombre { get; set; }
        public int valor { get; set; }
        public int idDocMat { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> idDocenteGrupo { get; set; }
    
        public virtual DocenteGrupo DocenteGrupo { get; set; }
        public virtual DocenteMateria DocenteMateria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareaAlumno> TareaAlumno { get; set; }
    }
}
